FROM node:lts-alpine as build
WORKDIR /app
ARG REACT_APP_NAME
ENV NODE_ENV=production
ENV REACT_APP_NAME=$REACT_APP_NAME
COPY "package.json" .
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

